name: steps examples

on:
  push:
    branches: [ "main" ]

jobs:
  marketplace:
    runs-on: ubuntu-latest
    steps:            
      - name: executa comando
        run: echo "Steps examples"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      - name: node verification
              node  -–version

            
